yellow_etl:
  outputs:
    dev:
      dataset: yellow_taxi
      job_execution_timeout_seconds: 300
      job_retries: 1
      # keyfile: /home/deepak/Documents/shreya project/gcp_dbt_etl_pipeline/service_key.json
      keyfile: /etl/dbt_permission.json
      location: US
      method: service-account
      priority: interactive
      project: dbt-pipeline-415806
      threads: 1
      type: bigquery
  target: dev
